services:
  api:
    image: php:7.2-apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
  pma:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMADB_USER: root
      PMADB_PASS: root
      PMADB_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    links:
      - db:db
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root